
all: ../../datasets/BLM2020_dataset.csv ../../datasets/BLM2021_dataset.csv ../../gen/data-preparation/temp/BLM2020_dataset.csv ../../gen/data-preparation/temp/BLM2021_dataset.csv


download_data: ../../datasets/BLM2020_dataset.csv ../../datasets/BLM2021_dataset.csv
	../../datasets/BLM2020_dataset.csv ../../datasets/BLM2021_dataset.csv: Rscript download_data.R
		Rscript download_data.R
	

data_cleaned: ../../gen/data-preparation/temp/BLM2020_dataset.csv ../../gen/data-preparation/temp/BLM2021_dataset.csv
	../../gen/data-preparation/temp/BLM2020_dataset.csv ../../gen/data-preparation/temp/BLM2021_dataset: ../../datasets/BLM2020_dataset.csv ../../datasets/BLM2021_dataset.csv preclean.R
		Rscript preclean.R